<a href="https://colab.research.google.com/github/1pawn0/time-series-forecasting-lab/blob/main/sklearn_ensemble_HistGradientBoostingRegressor_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
%pip install -qU polars scikit-learn

In [10]:
import os
from datetime import datetime
from pathlib import Path
from urllib.request import urlretrieve

import numpy as np
import polars as pl
from google.colab import userdata
from scipy.stats import randint, uniform
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV, TimeSeriesSplit
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler, RobustScaler, SplineTransformer

In [11]:
from urllib.request import urlretrieve
from pathlib import Path

csv_url: str = "https://www.cryptodatadownload.com/cdd/Gemini_BTCUSD_1h.csv"
data_dir: Path = Path("./data")
data_dir.mkdir(exist_ok=True, parents=True)
csv_file: Path = data_dir / "Gemini_BTCUSD_1h.csv"

if not csv_file.exists():
    urlretrieve(csv_url, csv_file)
    print(f"CSV file downloaded to {csv_file}")
else:
    print(f"CSV file already exists at {csv_file}")

import polars as pl

# Define the schema of df
df_schema: dict = {
    "date": pl.Datetime("ms"),
    "close": pl.Float64,
}
# Define which columns to load from the CSV
cols = list(df_schema.keys())
# Read the CSV file
df = (
    pl.read_csv(csv_file, columns=cols, skip_lines=1, schema_overrides=df_schema)
    .sort("date")
    .rename({"close": "price"})
)
# Fill the date gaps inside `df`
full_date_range = pl.datetime_range(
    start=df["date"][0],
    end=df["date"][-1],
    interval="1h",
    time_unit="ms",
    eager=True,
).to_frame(name="date")
df = full_date_range.join(df, on="date", how="left").interpolate().sort("date")
# Filter the dataset to only include data after a specific start date
df = df.filter(pl.col("date") > datetime(2016, 10, 30)).sort("date")
price_pct_changes_df = df.with_columns(
    pl.col("price").pct_change().shift(-1).alias("price_pct_change")
).sort("date")[:-1]
price_pct_changes_df

CSV file already exists at data/Gemini_BTCUSD_1h.csv

shape: (77_998, 3)
┌─────────────────────┬───────────┬──────────────────┐
│ date                ┆ price     ┆ price_pct_change │
│ ---                 ┆ ---       ┆ ---              │
│ datetime[ms]        ┆ f64       ┆ f64              │
╞═════════════════════╪═══════════╪══════════════════╡
│ 2016-10-30 01:00:00 ┆ 695.23    ┆ 0.014973         │
│ 2016-10-30 02:00:00 ┆ 705.64    ┆ 0.003713         │
│ 2016-10-30 03:00:00 ┆ 708.26    ┆ -0.001398        │
│ 2016-10-30 04:00:00 ┆ 707.27    ┆ -0.000014        │
│ 2016-10-30 05:00:00 ┆ 707.26    ┆ 0.0              │
│ …                   ┆ …         ┆ …                │
│ 2025-09-22 18:00:00 ┆ 112509.66 ┆ -0.002955        │
│ 2025-09-22 19:00:00 ┆ 112177.25 ┆ 0.006117         │
│ 2025-09-22 20:00:00 ┆ 112863.47 ┆ 0.00171          │
│ 2025-09-22 21:00:00 ┆ 113056.45 ┆ -0.002963        │
│ 2025-09-22 22:00:00 ┆ 112721.48 ┆ 0.00013          │
└─────────────────────┴───────────┴──────────────────┘

In [12]:
prices = price_pct_changes_df.with_columns([
    pl.col("date").dt.year().alias("year"),
    pl.col("date").dt.month().alias("month"),
    pl.col("date").dt.day().alias("day"),
    pl.col("date").dt.hour().alias("hour"),
    pl.col("date").dt.weekday().alias("weekday"),
    pl.col("date").dt.week().alias("week"),
    pl.col("date").dt.quarter().alias("quarter"),
    pl.col("date").dt.ordinal_day().alias("ordinal_day"),
]).sort('date')

In [13]:
hours: int = 24
lag_expressions: list[pl.Expr] = [pl.col("price_pct_change").shift(i).alias(f"pct_change_lag_{i}h") for i in range(1, hours + 1)]
rolling_expressions: list[pl.Expr] = [
    pl.col('price_pct_change').shift().rolling_mean(hours).alias(f'rolling_mean_{hours}h'),
    pl.col('price_pct_change').shift().rolling_std(hours).alias(f'rolling_std_{hours}h'),
    pl.col('price_pct_change').shift().rolling_var(hours).alias(f'rolling_var_{hours}h'),
    pl.col('price_pct_change').shift().rolling_skew(hours).alias(f'rolling_skew_{hours}h'),
    pl.col('price_pct_change').shift().rolling_kurtosis(hours).alias(f'rolling_kurtosis_{hours}h'),
    pl.col('price_pct_change').shift().ewm_mean_by(by='date', half_life='24h').alias(f'ewm_mean_{hours}h')
]
expr_list = lag_expressions + rolling_expressions

lagged_df = prices.with_columns(expr_list).drop_nulls().drop('price')

In [14]:
cyclical_periods = {
    'month': 12,
    'day': 31,
    'hour': 24,
    'weekday': 7,
    'week': 53,
    'quarter': 4,
    'ordinal_day': 366,
}

cols_to_process = [col for col in cyclical_periods if col in lagged_df.columns]

expressions = []
for col_name in cols_to_process:
    max_val = cyclical_periods[col_name]
    col_expr = pl.col(col_name)

    expressions.append(
        (col_expr * (2 * np.pi / max_val)).sin().alias(f"{col_name}_sine")
    )
    expressions.append(
        (col_expr * (2 * np.pi / max_val)).cos().alias(f"{col_name}_cosine")
    )

processed_df = lagged_df.with_columns(expressions).drop(cols_to_process)

processed_df

shape: (77_974, 47)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ date       ┆ price_pct_ ┆ year ┆ pct_change ┆ … ┆ quarter_si ┆ quarter_c ┆ ordinal_d ┆ ordinal_d │
│ ---        ┆ change     ┆ ---  ┆ _lag_1h    ┆   ┆ ne         ┆ osine     ┆ ay_sine   ┆ ay_cosine │
│ datetime[m ┆ ---        ┆ i32  ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆ f64        ┆      ┆ f64        ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2016-10-31 ┆ 0.013736   ┆ 2016 ┆ -0.018515  ┆ … ┆ -2.4493e-1 ┆ 1.0       ┆ -0.866025 ┆ 0.5       │
│ 01:00:00   ┆            ┆      ┆            ┆   ┆ 6          ┆           ┆           ┆           │
│ 2016-10-31 ┆ -0.00115   ┆ 2016 ┆ 0.013736   ┆ … ┆ -2.4493e-1 ┆ 1.0       ┆ -0.866025 ┆ 0.5       │
│ 02:00:00   ┆            ┆      ┆            ┆   ┆ 6          ┆           ┆           ┆           │
│ 2016-10-31 ┆ 0.0        ┆ 2016 ┆ -0.00115   ┆ … ┆ -2.4493e-1 ┆ 1.0       ┆ -0.866025 ┆ 0.5       │
│ 03:00:00   ┆            ┆      ┆            ┆   ┆ 6          ┆           ┆           ┆           │
│ 2016-10-31 ┆ 0.005869   ┆ 2016 ┆ 0.0        ┆ … ┆ -2.4493e-1 ┆ 1.0       ┆ -0.866025 ┆ 0.5       │
│ 04:00:00   ┆            ┆      ┆            ┆   ┆ 6          ┆           ┆           ┆           │
│ 2016-10-31 ┆ 0.0        ┆ 2016 ┆ 0.005869   ┆ … ┆ -2.4493e-1 ┆ 1.0       ┆ -0.866025 ┆ 0.5       │
│ 05:00:00   ┆            ┆      ┆            ┆   ┆ 6          ┆           ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2025-09-22 ┆ -0.002955  ┆ 2025 ┆ 0.000284   ┆ … ┆ -1.0       ┆ -1.8370e- ┆ -0.986731 ┆ -0.162366 │
│ 18:00:00   ┆            ┆      ┆            ┆   ┆            ┆ 16        ┆           ┆           │
│ 2025-09-22 ┆ 0.006117   ┆ 2025 ┆ -0.002955  ┆ … ┆ -1.0       ┆ -1.8370e- ┆ -0.986731 ┆ -0.162366 │
│ 19:00:00   ┆            ┆      ┆            ┆   ┆            ┆ 16        ┆           ┆           │
│ 2025-09-22 ┆ 0.00171    ┆ 2025 ┆ 0.006117   ┆ … ┆ -1.0       ┆ -1.8370e- ┆ -0.986731 ┆ -0.162366 │
│ 20:00:00   ┆            ┆      ┆            ┆   ┆            ┆ 16        ┆           ┆           │
│ 2025-09-22 ┆ -0.002963  ┆ 2025 ┆ 0.00171    ┆ … ┆ -1.0       ┆ -1.8370e- ┆ -0.986731 ┆ -0.162366 │
│ 21:00:00   ┆            ┆      ┆            ┆   ┆            ┆ 16        ┆           ┆           │
│ 2025-09-22 ┆ 0.00013    ┆ 2025 ┆ -0.002963  ┆ … ┆ -1.0       ┆ -1.8370e- ┆ -0.986731 ┆ -0.162366 │
│ 22:00:00   ┆            ┆      ┆            ┆   ┆            ┆ 16        ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [15]:
# Split the test set
split_point = lagged_df.height - (hours ** 2)
train_df = lagged_df.slice(0,split_point)
test_df = lagged_df.slice(split_point, lagged_df.height)
X_test, y_test = test_df.drop('price_pct_change'), test_df['price_pct_change']
X_test.shape, y_test.shape, test_df.shape, train_df.shape, lagged_df.shape

# Split the train and validation sets
split_point_val = int(0.8 * train_df.height)
X, y = train_df.drop('price_pct_change'), train_df['price_pct_change']
X_train = X.slice(0, split_point_val)
y_train = y.slice(0, split_point_val)
X_val = X.slice(split_point_val, train_df.height)
y_val = y.slice(split_point_val, train_df.height)
print(f" X_train: {X_train.shape}\n y_train: {y_train.shape}\n X_val: {X_val.shape}\n y_val: {y_val.shape}\n X_test: {X_test.shape}\n y_test: {y_test.shape}")

 X_train: (61918, 39)
 y_train: (61918,)
 X_val: (15480, 39)
 y_val: (15480,)
 X_test: (576, 39)
 y_test: (576,)

In [16]:
tscv = TimeSeriesSplit(n_splits=5)